### ISSUE TITLE
Drag & drop раздела в блок

### ISSUE THREAD

**Issue by alexzaporozhets** [msp4/worksheet-editor#2]
<img width="1127" alt="msp4" src="https://cloud.githubusercontent.com/assets/891472/8926718/89c134fe-351a-11e5-9056-6526db281bab.png">

**Comment by vladmokryi** [comment]
При перетаскивании раздела в блок:
-активным стает тот блок на который перетащили
-активным стает раздел который перетащили

**Comment by alexzaporozhets** [comment]
@Iryna-Ivasko проверяй, при редактировании возникает необходимость перетаскивать вопросы между разделами?

**Comment by Iryna-Ivasko** [comment]
Ні, у мене не виникло такої потреби. Це хіба якщо сильно накосячити з створенням анкети.

**Comment by Iryna-Ivasko** [comment]
все працює

**Comment by Iryna-Ivasko** [comment]
Добре було б додати ще копіювання цілого блоку в іншу анкету, але то вже, мабуть, пізніше можна буде додати

**Comment by vladmokryi** [comment]
Додав копіювання питань між розділами.
З приводу копіювання блоків в іншу анкету - думаю це нам не потрібно на клієнті, так як клієнт в дослідженні має тільки одну анкету
Це тільки якщо додати такий функціонал менеджеру

**Comment by Iryna-Ivasko** [comment]
Так, для клієнта не потрібно. А щодо менеджера, треба ще запитати в інших(для менеджера це було б дуже зручно)
